# Set the active competition phase and configuration
uint8 phase          # 1, 2, 3 or 4
bool open_hardware   # Using open hardware drone?
bool use_two_drones  # Phase 3 only: use two drones simultaneously?
---
bool success
string message
